name: Build and Publish Docker Image

on:
  push:
    branches: [ master,main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SHA7: ${GITHUB_SHA::7}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install

      - name: "Print short sha"
        run: echo "Short SHA is ${{ env.SHA7 }}"

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: vinodjothiram/cargarage
          tags: ${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cargarage_repo
          #IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7} .
          docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "Built Image $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7}"
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7}
          echo "Pushed Image $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7}"