
name: Deploy application with Terraform

on:
  release:
    tags:
      - dev*
      - qa*
      - uat*
      - prod*

jobs:
  deploy_terraform:
    name: Deploy with terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id = ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_LOG: TRACE

      - name: "intialize terraform"
        run: terraform -chdir=terraform/ init
        env:
          TF_LOG: DEBUG

      - name: "validate terraform"
        run: terraform -chdir=terraform/ validate
        env:
          TF_LOG: DEBUG

      - name: "plan terraform"
        run: terraform -chdir=terraform/ plan
        env:
          TF_LOG: DEBUG

      #- name: "Run terraform apply"
      #  run: terraform -chdir=terraform/ apply -auto-approve
